### ISSUE TITLE
[sew]

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/ielex2#10]
The proposed description is:

"Most generic verb for passing thread repeatedly through fabric or a material, using a needle, in order to join two or more parts or to make a pattern or motif."

I would strongly suggest leaving out of this part: "or to make a pattern or motif".
"Joining parts" and "making a pattern or motif" are likely to be expressed with completely different words.

The example sentence is nice :)

**Comment by cormacanderson** [comment]
That's fair enough. I'll take out the pattern or motif bit, or, alternatively, put in a clarifying sentence.
