### ISSUE TITLE
Clitics

### ISSUE THREAD

**Issue by mjkuemmel** [lingdb/ielex2#12]
Do we exclude clitics as "non-Swadesh"? I found some such judgments in [and] but without consequence. Exclusion of clitics would mean exclusion of all continuations of PIE *kʷe, which would mean that we would have to replace many entries by the real non-clitic Swadesh term.

**Comment by BrittaIrslinger** [comment]
Continuations of PIE *kʷe should not be excluded because they are clitics. They have to be excluded however, if they are not the default connectors.

**Comment by cormacanderson** [comment]
There's no general policy against clitics, but in practice the reduction to 200 meanings will mean that fewer of them will end up in the database, seeing as a lot of the grammatical words will be excluded, e.g. "at", "if", "in", "and" etc.
