### ISSUE TITLE
[suck]

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/ielex2#13]
The proposed description is:

"Most generic transitive verb for act of drawing in a substance by creating a practical vacuum in the mouth. Avoid baby-talk lexemes which may come from suckling, where different."

My question is:
If they are two different words in a language, one of them specialised for 'suckling' and the other for 'sucking' and they show a complementary distribution, should we take the word for 'sucking'?

My problem is:
I think that languages generally very often use obvious onomatopoeic words in both meanings. The first question that arises her is, are such words really usefull for our purposes? "Ignoring" of onomatopoeic words is a common rule in the comparative linguistics because (1) similarities are very likely to occur just by chance and (2) irregular sound changes are very likely to happen here. I think, both facts make them just **useless** for such linguistic comparisons that are our point in the whole project. The second question is if we are able at all -- given the great probability of random similarities and random sound changes -- to code cognate classes in a reasonable and convincing way here? I think, we aren't.

***

I'd suggest that we drop this term entirely.

**Comment by cormacanderson** [comment]
I think you are probably right, so I added this word to the list of possibilities for exclusion. Problem is that there are quite a lot of other meanings in there that are good candidates too.

**Comment by cormacanderson** [comment]
Given all the problems with this meaning that you outline above, we selected it for exclusion.
