### ISSUE TITLE
[neck]

### ISSUE THREAD

**Issue by obelyaev** [lingdb/ielex2#18]
There's no description of this term on the wiki yet, but during discussion it was pointed out that some languages distinguish between 'neck' as seen from the front and 'neck' as seen from behind. We decided to use the 'from the front' one as the Swadesh lexeme in case there's no neutral word, but I've looked through my Ossetic data and it seems that there is no special word for 'front neck' as such: the terms used is 'throat'. The back neck, on the other hand, does have a specific name. I would imagine that this situation recurs in a number of languages, therefore, I would suggest that, if no neutral term can be found, 'back neck' should be used.

**Comment by cormacanderson** [comment]
I agree, and actually remember the discussion as concluding that we should use the back of the neck if there is no word for the whole neck. I'll check my notes on that, but for me at least, this solution works. Hope to update the last of the meanings (the easiest ones) today.

**Comment by findell** [comment]
My recollection is the same as Cormac's.  If it's a hallucination, it's a shared one.

**Comment by obelyaev** [comment]
That's OK then, I probably got confused — I wasn't sure what the final decision was.
