### ISSUE TITLE
Add read-only fields to1 {mng., lng.} forms

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/ielex2#29]
Edited by @runjak:
Add (looked up, non-editable) columns for `is_excluded` and `is_loanword` in the 1 meaning and 1 language forms.

**Comment by runjak** [comment]
So I'm currently working on the backlog from the last session we've had on Tuesday.
I'm working to add in the `is_loanword` and `is_excluded` columns, but I've come accross the `Loan Event` column, which we also added. Do I remember correctly that this column should essentially have a checkbox that will correspond to a new (json) column, or is this supposed to be looked up from somewhere?
![loanevent](https://cloud.githubusercontent.com/assets/5417642/12479844/48e145aa-c03e-11e5-9f8f-db613d8943d1.png)

**Comment by runjak** [comment]
I see that the list of cognate classes already has a `Loan Event` column, so this should be the same column.
![loanevent](https://cloud.githubusercontent.com/assets/5417642/12509302/c3fe5eee-c101-11e5-8b26-723d84eca349.png)

**Comment by runjak** [comment]
I've added the `is_loan` and `is_excluded` columns with hg commit `018b0d6aea5a`.

**Comment by PaulHeggarty** [comment]
Your comment "I see that the list of cognate classes already has a Loan Event column, so this should be the same column" is only part right.  Remember that we are shifting from one system to another here, for entering loan events, and we need data on both systems to make the transition between them.  
Yes, there is a (new) Loan Event field in the cognate classes table.  Yes, this should be shown on both of these forms, alongside the root gloss.
But no, this does not replace the is_loan datum.  We need that as well!
Remember, is_loan and is_excluded are *not* single fields in any table, they are variables whose values are calculated by part of the script, by looking up values from multiple fields (in the lexemes table and the cognacy judgments table).  We want to get away from that system eventually, but we still need the data for now.  These are the variables that determine whether the alias letter is put between brackets, eg (A) not A.
I very specifically called these is_loan and is_excluded so that you could easily find the source of the data to put in these columns, because is_loan and is_excluded are the exact names given to these variables in the code, so you should be able to just search for them.

**Comment by PaulHeggarty** [comment]
Regarding:  
"I've added the is_loan and is_excluded columns with hg commit 018b0d6aea5a."
For the uninformed like Cormac and me -- does that mean they are already up on the website (I can't see them), or that they will be the next time it's updated?  Any idea when that will be?

**Comment by runjak** [comment]
Thanks for clarifying.
I never understood different than having the `is_loan` and `is_excluded` fields looked up.
Just the part of having the `Loan Event` field escaped my memory.
So the columns are looking like this at the moment:
![loanevent](https://cloud.githubusercontent.com/assets/5417642/12509773/20f14c9e-c105-11e5-856f-c1dcad70749b.png)

The missing thing is to put in the checkboxes for the `Loan Event` column and connect them to the database correctly.

**Comment by PaulHeggarty** [comment]
OK, all seems clear now.  It all looks right in the latest image file above!
(Change is_exc to is_excl, pps?)

**Comment by runjak** [comment]
Sure :)
The `Loan Event` column currently accessible in the cognate classes table is stored for each cognate class individually. But for the table of one meaning in all languages and all meanings in a language we have lexemes as entries. So I'll need help again to figure out where to store this best or if it actually are two things.
We could:
* Let the `Loan Event` column for lexemes be it's own independent entry to be stored with the lexemes.
* Somehow coordinate these two fields.

-----
This is not about the `is_loan` and `is_excl` fields, which are derived from the reliability choice for each Cognate Class, but about the `Loan Event` field added to Cognate classes earlier.
```
RELIABILITY_CHOICES = ( # used by Citation classes
        #("X", "Unclassified"), # change "X" to "" will force users to make
        ("A", "High"),         # a selection upon seeing this form
        ("B", "Good (e.g. should be double checked)"),
        ("C", "Doubtful"),
        ("L", "Loanword"),
        ("X", "Exclude (e.g. not the Swadesh term)"),
        )
```

**Comment by runjak** [comment]
After discussing this with @cormacanderson a likely solution to this problem was found:
* Keep the `Loan Event` column.
* Make the checkbox available iff there is only one Cognate Class associated with a given lexeme.
* Use the Cognate Class to store/retrieve the `Loan Event` information.

**Comment by runjak** [comment]
With hg commit `07337ed62c2c857f7628956151cb907ae79079b3` the `Loan Event` field is writable in both the `meanings x 1 language` and the `languages x 1 meaning` tables.
There is however currently a problem when editing this field in the `meanings x 1 language` table:
![screenshot_2016-01-31_11-26-42](https://cloud.githubusercontent.com/assets/5417642/12701592/ee85ee30-c80d-11e5-9d95-8d4495420ce2.png)
Several lexems may have the same cognate class and thus changing only one of the entries may not pass trough depending on the write order.
This is because once the change is written, other unchanged checkboxes will appear as a change to the current state and thus change stuff again.
Possible fixes for this are:
* Remembering which cognate class was changed already and not changing it again.
* Building a short JavaScript snippet that triggers all checkboxes belonging to a common cognate class at once.
The latter option may make more sense from the perspective of a user.

**Comment by runjak** [comment]
Update from today's meeting:
We don't want the `Loan Event` field to be editable from the `meanings x 1 language` and `languages x 1 meaning` views.
So I can just disable the current editing functionality for this I've been working on,
and should be able to close this issue very soon.

**Comment by runjak** [comment]
Hg commit `183a1290b39cd8cc40488600e70ef91c735c27ef` disables editing the `Loan Event` checkboxes.
