### ISSUE TITLE
[Add link to cognate class] does not work.

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/ielex2#30]
I can "add link to new cognate class" but can not "add link to cognate class" (neither from the entry nor from the list for the meaning).
It seems that during adding of new functionalities yesterday (?) something was broken.

**Comment by mjkuemmel** [comment]
I've had the same problem.

**Comment by runjak** [comment]
I've just updated the site with a fix from @aggtt, so the bug should now be removed.
I'll leave this issue open for a while so that you can verify that it's fixed and will close it later on.

**Comment by runjak** [comment]
I've just had a look at this with @PaulHeggarty and @cormacanderson and it appears to be working.
Therefore I'm closing this issue.
