### ISSUE TITLE
Add a feature to filter boolean fields.

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/ielex2#34]
Edit by @runjak:
Add a feature allowing record rows for excluded entries (i.e. not Swadesh term) to be filtered out, i.e. not visible

**Comment by leszekjocz** [comment]
There is an issue related to the topic I would like to ask for.
As I see, the "reliability" judgement "exclude (e.g. not the Swadesh term)" from the old interface is not synchronized with the "Not Swh" column in the new interface. I would like to make sure that the judgements from the old fields (~from the old interface) will be merged with the judgements from the new field (~from the new interface) and that we do not have to mark "excluded" entries one more time as "Not Swh" in the new interface.

**Comment by runjak** [comment]
I think this issue is very similar to #6, except for the addition by @leszekjocz.
Thus I renamed it to filtering boolean fields.

**Comment by runjak** [comment]
Hg commits `f911e0815ebe98a4a9ff3e093611633288a7e843` and `8ec9e67deac2be3173e12746492b0978c491d8c5` address this issue and will be deployed with the next update.
