### ISSUE TITLE
Adjust count columns

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/ielex2#35]
We should have count columns with names 'Mgs','Lex.','Entd'.
These columns should reflect counts for:
Mgs: The number of meanings in each language
Lex.: The number of lexemes in each language
Entd: The number of entries in each language

**Comment by runjak** [comment]
I've implemented this in hg commit `fbec4408b4659e3cade0829c211bcd951ecfba16`.
There is a part of the code that doesn't use the ORM right now that I'd like to discuss with Andrew before deployment.

**Comment by runjak** [comment]
The code is reviewed and up in shape.
This feature will get deployed with the next update as expected.
