### ISSUE TITLE
Add time fields to languages table

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/ielex2#37]
Edit by @runjak:
In the languages table:
* Add two fields carrying numbers
* Name these fields `tip mean time depth BP [yrs]` and `tip std deviation [yrs]`

**Comment by runjak** [comment]
![time](https://cloud.githubusercontent.com/assets/5417642/12548666/4cdc0290-c358-11e5-9203-0da5699ccc03.png)
This feature has been implemented and will get rolled out soon.
