### ISSUE TITLE
Do we need a new database table for [Language Branches]?

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/ielex2#40]
Can the necessary functionality, i.e. filtering by branch, be got from the SndCmp index numbers?

**Comment by cormacanderson** [comment]
View the email from Michael of 06.12.2015

**Comment by cormacanderson** [comment]
@runjak @PaulHeggarty

**Comment by PaulHeggarty** [comment]
We already have such a table, it's just not viewable or editable on the website yet.
