### ISSUE TITLE
Citation forms for non-canonical subject marking

### ISSUE THREAD

**Issue by ks10007** [lingdb/ielex2#8]
Any ideas on which citation form to use for verbal notions with non-canonical subject marking, i.e. "to me is fear" (Romanian)  or "fear is on me" (Irish)? Do we choose a person at random (e.g. 1st person)? Alternatives such as "be fear [on]" as citation form seem rather unnatural. 
Romanian actually has a standard citation form for these constructions, but it might not be the same as in other languages.

**Comment by tonyakdewey** [comment]
Germanic prefers to use 3rd person here, so that would be my suggestion.  Of course, we have the gender-neutral 3rd person reflexive. This might not work if you need to pick a gender for 3rd person, since the solution simply presents another problem.

**Comment by tonyakdewey** [comment]
How about we just use whatever we need to use to find the item in a dictionary?  i.e., follow language-specific conventions?

**Comment by cormacanderson** [comment]
The proposal here by @tonyakdewey seems very reasonable to me, although we should keep an eye on these as to how we code them for cognacy. I'll close this issue for now though, and we'll take the dictionary form as policy. Is that good by you @ks10007 ?
